namespace Octopus.Runtime;

/// <summary>
/// Generates a multi-stage Dockerfile for .NET web projects. Written into the
/// worker's throwaway workspace copy only — never committed to the user's repo.
/// Targets .NET 10, listens on 8080 (matches the default container port).
/// </summary>
public static class DockerfileGenerator
{
    public const string SdkImage = "mcr.microsoft.com/dotnet/sdk:10.0";
    public const string RuntimeImage = "mcr.microsoft.com/dotnet/aspnet:10.0";

    public static string ForDotnet(string projectRelativePath, string assemblyName)
    {
        var proj = projectRelativePath.Replace('\\', '/');
        var dll = assemblyName.EndsWith(".dll", StringComparison.OrdinalIgnoreCase)
            ? assemblyName
            : assemblyName + ".dll";
        return
            "# Generated by Octopus dotnet buildpack (workspace copy only — not committed to your repo).\n" +
            $"FROM {SdkImage} AS build\n" +
            "WORKDIR /src\n" +
            "COPY . .\n" +
            $"RUN dotnet publish \"{proj}\" -c Release -o /app/publish --nologo\n" +
            $"FROM {RuntimeImage} AS final\n" +
            "WORKDIR /app\n" +
            "ENV ASPNETCORE_URLS=http://+:8080\n" +
            "EXPOSE 8080\n" +
            "COPY --from=build /app/publish .\n" +
            $"ENTRYPOINT [\"dotnet\", \"{dll}\"]\n";
    }
}
